
TEST_KEY_SECRET = 'sk_test_9z2RIuNiv6lqUiBX7DpcY8z0'
TEST_KEY_PUBLISHABLE = 'pk_test_esYpdm56QsBE1f41MLlBdkrp'
PRO_KEY_SECRET = 'sk_live_MhB6JKJHszct0WZWCAqbwATU'
PRO_KEY_PUBLISHABLE = 'pk_live_nBNsfrt1S9Bjah9hTO8yohPJ'
