# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import web_store.encryption


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('img_name', models.CharField(max_length=128)),
                ('rating', models.CharField(max_length=1)),
                ('price', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_text', web_store.encryption.EncryptedCharField(max_length=50, unique=True)),
                ('claimed', models.BooleanField(default=False)),
                ('service', models.CharField(max_length=10)),
                ('claimed_by', web_store.encryption.EncryptedCharField(blank=True, max_length=128, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_store.Game')),
            ],
        ),
    ]
