# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
